/**
 * The plugin side of the host protocol.
 *
 * Shared by every plugin so the wire format has one definition on this side too. A
 * mismatch with `@ddtx/plugin-sdk`'s `readPrefixed` does not throw — it reads garbage —
 * so the two are deliberately small and deliberately symmetrical.
 *
 * Compiled with `runtime: stub` and `use: ["abort="]`, which strips even the standard
 * `abort` import. That is what lets a plugin instantiate against an empty
 * `importObject`: there is no host function for it to call. Do not add anything here
 * that needs an import.
 */

/** Bump allocator. Never freed — a plugin run is short and then the module is dropped. */
let heapPtr: i32 = 4096;

export function alloc(size: i32): i32 {
  const ptr = heapPtr;
  heapPtr = (heapPtr + size + 15) & ~15;
  const needed = (heapPtr + 65535) >>> 16;
  const current = memory.size();
  if (needed > current) memory.grow(needed - current);
  return ptr;
}

/** Write a length-prefixed UTF-8 string and return its pointer. */
export function emit(text: string): i32 {
  const buffer = String.UTF8.encode(text);
  const length = buffer.byteLength;
  const ptr = alloc(length + 4);
  store<i32>(ptr, length);
  memory.copy(ptr + 4, changetype<usize>(buffer), length);
  return ptr;
}

/** Read the host's result. Raw UTF-8, not prefixed — the host passes the length. */
export function readResult(ptr: i32, len: i32): string {
  return String.UTF8.decodeUnsafe(ptr, len);
}

/* ── commands ──────────────────────────────────────────────────────────────── */

export function log(text: string): i32 {
  return emit('{"op":"log","text":"' + escape(text) + '"}');
}

export function ask(prompt: string, field: string): i32 {
  return emit('{"op":"ask","prompt":"' + escape(prompt) + '","field":"' + escape(field) + '"}');
}

export function session(request: string): i32 {
  return emit('{"op":"session","request":"' + escape(request) + '"}');
}

export function read(request: string): i32 {
  return emit('{"op":"read","request":"' + escape(request) + '"}');
}

/** `values` is pre-built JSON, because building a map here would need a runtime. */
export function write(request: string, values: string): i32 {
  return emit('{"op":"write","request":"' + escape(request) + '","values":' + values + "}");
}

export function done(text: string): i32 {
  return emit('{"op":"done","status":"ok","text":"' + escape(text) + '"}');
}

export function failed(text: string): i32 {
  return emit('{"op":"done","status":"failed","text":"' + escape(text) + '"}');
}

/**
 * Escape a string for embedding in JSON.
 *
 * Hand-rolled because there is no JSON library here. Only the characters that would
 * break the document are handled: a request name from the database can contain quotes
 * and backslashes, and the French labels contain no control characters.
 */
export function escape(text: string): string {
  let out = "";
  for (let i = 0; i < text.length; i++) {
    const c = text.charAt(i);
    if (c == '"') out += '\\"';
    else if (c == "\\") out += "\\\\";
    else if (c == "\n") out += "\\n";
    else if (c == "\r") out += "\\r";
    else if (c == "\t") out += "\\t";
    else out += c;
  }
  return out;
}

/**
 * Whether the host reported success.
 *
 * A substring test rather than a JSON parse: the host's results are generated by
 * `JSON.stringify` of a small closed union, so `"ok":true` appears exactly when the
 * command succeeded and nowhere else.
 */
export function succeeded(result: string): bool {
  return result.includes('"ok":true');
}

/** Pull one string field out of the host's result. Returns "" when absent. */
export function field(result: string, name: string): string {
  const key = '"' + name + '":"';
  const at = result.indexOf(key);
  if (at < 0) return "";
  const from = at + key.length;
  let to = from;
  while (to < result.length) {
    const c = result.charAt(to);
    if (c == '"' && result.charAt(to - 1) != "\\") break;
    to += 1;
  }
  return result.substring(from, to);
}
