/**
 * Demo mode: drive the whole app against the database with no car attached.
 *
 * The original does this with `options.simulation_mode`, which makes
 * `EcuRequest.send_request` return the request's `replybytes` instead of calling
 * the ELM. That canned data is real and well-formed — 510,615 of 541,061 requests
 * carry it (94.4%), all valid hex, and its first byte is the positive-response
 * SID in 74,513 of 74,528 sampled cases, so it has exactly the frame layout a
 * live response would.
 *
 * It is also often *short*: 11.7% of canned replies are shorter than their
 * request's own `minbytes`, so a faithful replay leaves a lot of fields blank.
 * That is fine for spot-checking a value and poor for building a UI, where you
 * need to see every widget populated and find out how long the text gets. Hence
 * three fill modes, `"pad"` by default:
 *
 * | mode | behaviour |
 * |---|---|
 * | `canned` | `replybytes` verbatim — exactly what the Qt app's demo mode shows |
 * | `pad` | `replybytes`, extended with generated bytes to the length the fields need |
 * | `synthetic` | fully generated — every widget populated, useful for layout stress |
 *
 * Generated bytes are deterministic, derived from the request name and a seed, so
 * a screen looks the same on every refresh instead of flickering. `drift` opts
 * into slow variation when you want to watch a refresh actually happen.
 *
 * None of this is a vehicle simulator. Values are arbitrary and are not
 * physically plausible or self-consistent; the UI must label the mode clearly.
 */

import type { BoundRequest } from "@ddtx/codec";
import type { EcuLink, RequestHint } from "./link.js";

export type FillMode = "canned" | "pad" | "synthetic";

export interface SimulatedLinkOptions {
  /** Default `"pad"`. */
  fill?: FillMode;
  /** Varies generated bytes so values move between refreshes. Default `false`. */
  drift?: boolean;
  /** Changes every generated value while staying reproducible. Default `1`. */
  seed?: number;
  /** Artificial round-trip delay in ms, to expose loading states. Default `0`. */
  latencyMs?: number;
}

/**
 * How many bytes of response the request's own fields reach into.
 *
 * `firstbyte` is 1-based and a field can start part-way through a byte, so the
 * end of a field is `firstbyte - 1 + ceil((bitscount + bitoffset) / 8)`. The
 * result is the maximum over all receive fields, floored at `minbytes`.
 */
export function requiredResponseBytes(request: BoundRequest): number {
  let needed = request.def.minbytes ?? 0;

  for (const [name, item] of Object.entries(request.def.receivebyte_dataitems ?? {})) {
    const data = request.data.get(name);
    if (data === undefined) continue; // dangling reference; reported by db-split
    const start = (item.firstbyte ?? 0) - 1;
    const span = Math.ceil((data.bitscount + (item.bitoffset ?? 0)) / 8);
    needed = Math.max(needed, start + span);
  }

  return needed;
}

/** FNV-1a, so a request name maps to a stable seed without a crypto dependency. */
function hashString(text: string): number {
  let hash = 0x811c9dc5;
  for (let i = 0; i < text.length; i++) {
    hash ^= text.charCodeAt(i);
    hash = Math.imul(hash, 0x01000193);
  }
  return hash >>> 0;
}

/** mulberry32 — small, fast, and reproducible across platforms. */
function makeRandom(seed: number): () => number {
  let state = seed >>> 0;
  return () => {
    state = (state + 0x6d2b79f5) >>> 0;
    let t = state;
    t = Math.imul(t ^ (t >>> 15), t | 1);
    t ^= t + Math.imul(t ^ (t >>> 7), t | 61);
    return ((t ^ (t >>> 14)) >>> 0) / 4294967296;
  };
}

function generateHex(seed: number, byteCount: number): string {
  const random = makeRandom(seed);
  let out = "";
  for (let i = 0; i < byteCount; i++) {
    out += Math.floor(random() * 256)
      .toString(16)
      .padStart(2, "0")
      .toUpperCase();
  }
  return out;
}

/** Split hex into space-separated bytes, the shape `ELM.request` returns. */
function spaced(hex: string): string {
  return (hex.match(/.{1,2}/g) ?? []).join(" ");
}

export class SimulatedLink implements EcuLink {
  readonly kind = "simulated" as const;

  private readonly fill: FillMode;
  private readonly drift: boolean;
  private readonly seed: number;
  private readonly latencyMs: number;

  /** Bumped on every `clearCache`, i.e. once per screen refresh, to drive drift. */
  private generation = 0;

  private readonly byName: ReadonlyMap<string, BoundRequest>;
  /** Request-template frame → request, for calls that arrive without a hint. */
  private readonly byFrame: Map<string, BoundRequest>;

  constructor(requests: ReadonlyMap<string, BoundRequest>, options: SimulatedLinkOptions = {}) {
    this.byName = requests;
    this.fill = options.fill ?? "pad";
    this.drift = options.drift ?? false;
    this.seed = options.seed ?? 1;
    this.latencyMs = options.latencyMs ?? 0;

    this.byFrame = new Map();
    for (const request of requests.values()) {
      const frame = (request.def.sentbytes ?? "").toUpperCase();
      // First definition wins, matching how the original's dict-keyed lookup
      // behaves when two requests share a template.
      if (frame.length > 0 && !this.byFrame.has(frame)) this.byFrame.set(frame, request);
    }
  }

  async request(frame: string, hint?: RequestHint): Promise<string> {
    if (this.latencyMs > 0) {
      await new Promise((resolve) => setTimeout(resolve, this.latencyMs));
    }

    const compact = frame.replace(/\s+/g, "").toUpperCase();
    const request = this.resolve(compact, hint);

    // Nothing in the database describes this frame. A real ECU would answer
    // "service not supported"; saying so beats inventing a positive reply.
    if (request === undefined) return spaced(`7F${compact.slice(0, 2)}11`);

    const canned = (request.def.replybytes ?? "").toUpperCase();
    const needed = requiredResponseBytes(request);

    if (this.fill === "canned") {
      // Faithful: an absent canned reply yields nothing to decode, exactly as
      // `send_request` returns "" and every field comes back null.
      return spaced(canned);
    }

    const name = request.def.name;
    const seed = hashString(name) ^ Math.imul(this.seed, 0x9e3779b1);
    const varied = this.drift ? (seed ^ Math.imul(this.generation, 0x85ebca6b)) >>> 0 : seed;

    if (this.fill === "synthetic") {
      // Keep the real response SID so anything matching on it still works.
      const sid = canned.slice(0, 2) || positiveResponseSid(compact);
      const body = generateHex(varied, Math.max(0, needed - 1));
      return spaced((sid + body).slice(0, Math.max(2, needed * 2)));
    }

    // With no canned reply at all, still lead with the positive-response SID.
    // A real frame always does, `firstbyte` is 1-based *including* it, and some
    // screens read byte 1 directly — so a random first byte is both unrealistic
    // and misleading in a trace.
    const base = canned.length > 0 ? canned : positiveResponseSid(compact);
    const baseBytes = Math.floor(base.length / 2);
    if (baseBytes >= needed) return spaced(base);
    return spaced(base + generateHex(varied, needed - baseBytes));
  }

  /**
   * Find the request behind a frame.
   *
   * The hint is authoritative when present. Without one, an exact template match
   * comes first, then a same-length match on the service and sub-function bytes —
   * which is how a frame with user-supplied input bytes still finds its request,
   * since inputs only overwrite bytes within the template.
   */
  private resolve(compact: string, hint?: RequestHint): BoundRequest | undefined {
    if (hint !== undefined) {
      const named = this.byName.get(hint.requestName);
      if (named !== undefined) return named;
    }

    const exact = this.byFrame.get(compact);
    if (exact !== undefined) return exact;

    for (const [template, request] of this.byFrame) {
      if (template.length !== compact.length) continue;
      if (template.slice(0, 4) === compact.slice(0, 4)) return request;
    }
    return undefined;
  }

  clearCache(): void {
    this.generation += 1;
  }
}

/** `SID + 0x40`, the positive-response service id. */
function positiveResponseSid(frame: string): string {
  const sid = Number.parseInt(frame.slice(0, 2), 16);
  if (Number.isNaN(sid)) return "00";
  return ((sid + 0x40) & 0xff).toString(16).padStart(2, "0").toUpperCase();
}
