#!/usr/bin/env python3
"""Generate `packages/core/src/addressing.ts` — functional address → CAN ids.

A functional address like `26` is not something you can put on a CAN bus; it has to
be translated into a transmit and receive id (`765` / `76D`, or the 29-bit
`18DA26F1` / `18DAF126`). DDT4All keeps that mapping in `resources/projects.json`
as `dnat`/`snat` (11-bit) and `dnat_ext`/`snat_ext` (29-bit), and the scanner needs
it to address anything at all.

**The per-project structure in that file is redundant.** All 185 projects carry
byte-identical tables — verified by hashing each project's four tables and finding
exactly one distinct result, with zero conflicting entries across the union. So
what looks like 96,200 entries is really 520, and this emits them once.

`addressing` (address → short and long ECU name) is uniform too: one distinct table
across all 185, 353 entries, and every `dnat` address has a name.

Usage:
    python3 tools/reference/gen-addressing.py <ddt4all>/src/ddt4all/resources/projects.json
"""

import hashlib
import json
import sys


def main() -> None:
    source = sys.argv[1]
    out = sys.argv[2] if len(sys.argv) > 2 else "packages/core/src/addressing.ts"

    projects = json.load(open(source, encoding="utf-8"))["projects"]

    # Refuse to emit if the assumption above ever stops holding: silently picking
    # one project's tables when they had diverged would misaddress ECUs.
    signatures = {
        hashlib.sha256(
            json.dumps(
                {k: (p.get(k) or {}) for k in ("dnat", "snat", "dnat_ext", "snat_ext", "addressing")},
                sort_keys=True,
            ).encode()
        ).hexdigest()
        for p in projects.values()
    }
    if len(signatures) != 1:
        raise SystemExit(
            f"expected one addressing table across all projects, found {len(signatures)} — "
            "the tables have diverged and this generator's assumption no longer holds"
        )

    any_project = next(iter(projects.values()))
    dnat = any_project["dnat"]
    snat = any_project["snat"]
    dnat_ext = any_project["dnat_ext"]
    snat_ext = any_project["snat_ext"]
    names = any_project["addressing"]

    def emit_map(name: str, table: dict, comment: str) -> list[str]:
        lines = [f"/** {comment} */", f"const {name}: Readonly<Record<string, string>> = {{"]
        for key in sorted(table):
            lines.append(f"  {json.dumps(key.upper())}: {json.dumps(table[key])},")
        lines += ["};", ""]
        return lines

    lines = [
        "/**",
        " * Functional address → CAN identifiers, and address → ECU name.",
        " *",
        " * Generated by `tools/reference/gen-addressing.py` from DDT4All's",
        " * `resources/projects.json`. Do not edit by hand.",
        " *",
        " * A functional address (`26`) cannot be put on a bus; it has to become a",
        " * transmit/receive id pair. DDT4All stores this per vehicle project, but all",
        f" * 185 projects carry byte-identical tables, so it is emitted once here:",
        f" * {len(dnat)} 11-bit pairs and {len(dnat_ext)} 29-bit pairs.",
        " *",
        " * `dnat`/`snat` are DDT4All's names, from the DiagOnCAN convention: the",
        " * *diagnostic* address translated to a transmit id, and the *source* address",
        " * to the id the ECU answers on.",
        " */",
        "",
    ]
    lines += emit_map("TX_11BIT", dnat, "Functional address → 11-bit transmit id (`dnat`).")
    lines += emit_map("RX_11BIT", snat, "Functional address → 11-bit receive id (`snat`).")
    lines += emit_map("TX_29BIT", dnat_ext, "Functional address → 29-bit transmit id (`dnat_ext`).")
    lines += emit_map("RX_29BIT", snat_ext, "Functional address → 29-bit receive id (`snat_ext`).")

    lines += ["/** Functional address → [short name, long name]. */",
              "const ADDRESS_NAMES: Readonly<Record<string, readonly [string, string]>> = {"]
    for key in sorted(names):
        value = names[key]
        short = value[0] if isinstance(value, list) and value else str(value)
        long = value[1] if isinstance(value, list) and len(value) > 1 else short
        lines.append(f"  {json.dumps(key.upper())}: [{json.dumps(short, ensure_ascii=False)}, "
                     f"{json.dumps(long, ensure_ascii=False)}],")
    lines += ["};", ""]

    lines += [
        "export interface CanAddressing {",
        "  /** Transmit id: 3 hex chars for 11-bit, 8 for 29-bit. */",
        "  idTx: string;",
        "  idRx: string;",
        "  /** True when this is a 29-bit (extended) pair. */",
        "  extended: boolean;",
        "}",
        "",
        "/**",
        " * CAN ids for a functional address, preferring 11-bit.",
        " *",
        " * 11-bit first because that is what the original tries first, and because an",
        " * ECU reachable both ways answers the same either way. `undefined` means the",
        " * address is not mapped — `elm.py:addr_exist` — and must be skipped rather",
        " * than guessed at.",
        " */",
        "export function canAddressing(address: string): CanAddressing | undefined {",
        "  const key = address.trim().toUpperCase();",
        "  const tx = TX_11BIT[key];",
        "  const rx = RX_11BIT[key];",
        "  if (tx !== undefined && rx !== undefined) return { idTx: tx, idRx: rx, extended: false };",
        "",
        "  const txExt = TX_29BIT[key];",
        "  const rxExt = RX_29BIT[key];",
        "  if (txExt !== undefined && rxExt !== undefined) {",
        "    return { idTx: txExt, idRx: rxExt, extended: true };",
        "  }",
        "  return undefined;",
        "}",
        "",
        "/** Is this address mapped to CAN ids at all? `elm.py:addr_exist`. */",
        "export function isAddressMapped(address: string): boolean {",
        "  return canAddressing(address) !== undefined;",
        "}",
        "",
        "/**",
        " * What sits at this address, long name preferred.",
        " *",
        " * The index's own `group` is free text and inconsistent; this table is the",
        " * canonical naming, and it is what makes a scan result readable.",
        " */",
        "export function addressName(address: string, form: \"short\" | \"long\" = \"long\"): string | undefined {",
        "  const entry = ADDRESS_NAMES[address.trim().toUpperCase()];",
        "  if (entry === undefined) return undefined;",
        "  return form === \"short\" ? entry[0] : entry[1];",
        "}",
        "",
        "/** Every address with a CAN mapping, sorted. What a full sweep covers. */",
        "export function mappedCanAddresses(): string[] {",
        "  return [...new Set([...Object.keys(TX_11BIT), ...Object.keys(TX_29BIT)])].sort();",
        "}",
        "",
    ]

    with open(out, "w", encoding="utf-8") as handle:
        handle.write("\n".join(lines))
    print(
        f"wrote {out}: {len(dnat)} 11-bit pairs, {len(dnat_ext)} 29-bit pairs, "
        f"{len(names)} address names"
    )


if __name__ == "__main__":
    main()
