#!/usr/bin/env python3
"""Generate `packages/core/src/projects.ts` — vehicle code → model name.

The ECU index labels each vehicle with a Renault project code (`X64`, `HFEPh2`,
`J32V`). Those are what the database stores and what the codec matches on, but
nobody outside the factory reads them, so the UI needs the model name.

DDT4All carries the mapping in `resources/projects.json`, keyed by a display
string of the form `[CODE] - Model Name`. This pulls out the code and the model
half. 136 of the 140 codes the database actually uses are covered; the rest keep
their code as their label.

Usage:
    python3 tools/reference/gen-projects.py <ddt4all>/src/ddt4all/resources/projects.json
"""

import json
import re
import sys

# "[HFEPH2] - Renault Kadjar Ph2" → "Renault Kadjar Ph2"
LABEL = re.compile(r"^\s*\[[^\]]*\]\s*-\s*(.+?)\s*$")


def main() -> None:
    source = sys.argv[1]
    out = sys.argv[2] if len(sys.argv) > 2 else "packages/core/src/projects.ts"

    projects = json.load(open(source, encoding="utf-8"))["projects"]

    names: dict[str, str] = {}
    for display, entry in projects.items():
        code = (entry.get("code") or "").strip()
        if not code or code.upper() == "ALL":
            continue
        matched = LABEL.match(display)
        name = matched.group(1) if matched else display.strip()
        # Keyed upper-case: the database spells the same code both ways
        # ("HFEPh2" in an ECU file, "HFEPH2" here).
        names[code.upper()] = name

    lines = [
        "/**",
        " * Vehicle project code → model name.",
        " *",
        " * Generated by `tools/reference/gen-projects.py` from DDT4All's",
        f" * `resources/projects.json` ({len(names)} entries). Do not edit by hand.",
        " *",
        " * The database stores project codes and the codec matches on them, so they stay",
        " * the identity throughout; this is display text only.",
        " */",
        "const PROJECT_NAMES: Readonly<Record<string, string>> = {",
    ]
    for code in sorted(names):
        lines.append(f"  {json.dumps(code)}: {json.dumps(names[code], ensure_ascii=False)},")
    lines += [
        "};",
        "",
        "/**",
        " * The model name for a project code, or the code itself when unknown.",
        " *",
        " * Four codes the database uses have no entry (`X77AbsOnly`, `xBJ`, `xPIV`, and",
        " * the XML artifact `#text`), and showing the raw code beats showing nothing.",
        " */",
        "export function projectLabel(code: string): string {",
        "  return PROJECT_NAMES[code.trim().toUpperCase()] ?? code;",
        "}",
        "",
        "/** Is this a code we can name? Useful for sorting the named ones first. */",
        "export function hasProjectName(code: string): boolean {",
        "  return PROJECT_NAMES[code.trim().toUpperCase()] !== undefined;",
        "}",
        "",
    ]

    with open(out, "w", encoding="utf-8") as handle:
        handle.write("\n".join(lines))
    print(f"wrote {out} with {len(names)} names")


if __name__ == "__main__":
    main()
